MussicBapp-master/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show]
  root to: "bands#index"

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create]
  end

  resources :notes, only: [:destroy]
end

MussicBapp-master/app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :track_type, :album_id, :lyrics, presence: true

  belongs_to :album

  has_one :band, through: :album, source: :band

  has_many :notes, dependent: :destroy

  def select_if_regular
    "checked" if self.track_type == "Regular"
  end
  def select_if_bonus
    "checked" if self.track_type == "Bonus"
  end
end

MussicBapp-master/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :require_login

  def new
    @track = Track.new
    @track.album_id = params[:album_id]
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to album_url(@track.album_id)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def destroy
    track = Track.find(params[:id])
    track.destroy
    redirect_to album_url(track.album_id)
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  private
  def track_params
    params.require(:track).permit(:name,:album_id,:track_type,:lyrics)
  end

end

MussicBapp-master/app/helpers/tracks_helper.rb
module TracksHelper
  def ugly_lyrics(text)
    text.split("\n").map{ |line| "♫" + line }.join("\n")
  end
end

MussicBapp-master/app/views/tracks/_form.html.erb
<%= make_authenticity_token %>

<label>
  Name
  <input type="text" name="track[name]" value="<%=@track.name%>">
</label>
<br>

<label>
  Album
  <select name="track[album_id]">
    <% Album.all.each do |album| %>
    <option value="<%=album.id%>" <%='selected' if @track.album_id == album.id%>>
      <%=album.name%>
    </option>
    <% end %>
  </select>
</label>
<br>

<label >
  Regular Track
  <input type="radio" name="track[track_type]"
  value="Regular" <%=@track.select_if_regular%> >
</label>
<label >
  Bonus Track
  <input type="radio" name="track[track_type]"
  value="Bonus" <%=@track.select_if_bonus%> >
</label>
<br>

<label>
  Lyrics
  <textarea name="track[lyrics]"><%=@track.lyrics%></textarea>
</label>
<br>

<input type="submit">

MussicBapp-master/app/views/tracks/edit.html.erb
<h1>Edit Track: <%=@track.name%></h1>

<%= flash_now_information %>

<form id="new_track" action="<%=track_url(@track)%>" method="post">

  <input type="hidden" name="_method" value="PATCH">

  <%= render "form" %>

</form>

MussicBapp-master/app/views/tracks/new.html.erb
<h1>Add new Track</h1>

<%= flash_now_information %>

<form id="new_track" action="<%=tracks_url%>" method="post">

  <%= render "form" %>

</form>

MussicBapp-master/app/views/tracks/show.html.erb
<h1>Track: <%=@track.name%> - <%=@track.track_type%></h1>

<form id="edit_this" action="<%=edit_track_url(@track)%>" method="get">
  <%= make_authenticity_token %>
  <input type="submit" value="Edit Track">
</form>
<form id="delete_this" action="<%=track_url(@track)%>" method="post">
  <%= make_authenticity_token %>
  <input type="hidden" name="_method" value="DELETE">
  <input data-confirm='Are you sure?' value="Delete Track" type="submit">
</form>
<br>

<a href="<%=album_url(@track.album_id)%>">Back to <%=@track.album.name%></a>

<h3>Lyrics</h3>
<br>
<pre>
  <%=ugly_lyrics(@track.lyrics)%>
</pre>
<br>
<h3>Notes</h3>
<ul>
  <% @track.notes.each do |note| %>
    <li><%= render "notes/note", note: note %></li>
  <% end %>
  <li><%=render "notes/form"%></li>
</ul>