MyWorstProject-master/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :goals do
    post 'complete', to: "goals#complete"
  end
  resources :comments, only: [:create, :destroy]
end

MyWorstProject-master/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :user_id, :commentable, presence: true

  belongs_to :user

  belongs_to :commentable, polymorphic: true

end

MyWorstProject-master/app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :content, :access, :user_id, :completion, presence: true
  validates :access, inclusion: { in: ["Public", "Private"]}

  belongs_to :author,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id

  has_many :comments, as: :commentable

  def check_if_public
    self.access == "Public" ? "checked" : ""
  end

  def check_if_private
    self.access == "Private" ? "checked" : ""
  end

  def complete_goal
    self.completion = "Complete"
  end

  def is_complete?
    self.completion == "Complete"
  end
end

MyWorstProject-master/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 5, allow_nil: true }

  has_many :comments, as: :commentable

  has_many :goals

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(username,password)
    user = User.find_by_username(username)
    return nil unless user && user.is_password?(password)
    user
  end

  after_initialize :ensure_session_token

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

MyWorstProject-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def signed_in?
    !!current_user
  end

  def log_in_user!(user)
    session[:token] = user.reset_session_token!
  end

  def log_out_user!
    current_user.reset_session_token!
    session[:token] = nil
    redirect_to new_session_url
  end

  def current_user
    return nil if session[:token].nil?
    @cu ||= User.find_by(session_token: session[:token])
  end

  def ensure_logged_in
    unless signed_in?
      redirect_to new_session_url
    end
  end
end

MyWorstProject-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :ensure_logged_in

  def new
    @comment = Comment.new
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      comment_redirect
    else
      flash[:errors] = @comment.errors.full_messages
      comment_redirect
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    comment_redirect
  end

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end

  def comment_redirect
    redirect_to self.send("#{@comment.commentable_type.downcase}_url".to_sym,
      @comment.commentable_id)
  end

end

MyWorstProject-master/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :ensure_logged_in

  def index
    @goals = Goal.where(access: "Public")
    render :index
  end

  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.completion = "Incomplete"
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
    render :show
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    redirect_to goals_url
  end

  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def complete
    @goal = Goal.find(params[:goal_id])
    @goal.complete_goal
    unless @goal.save
      flash[:errors] = @goal.errors.full_messages
    end
    redirect_to goal_url(@goal)
  end

  private
  def goal_params
    params.require(:goal).permit(:title, :content, :access)
  end
end

MyWorstProject-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])
    if @user
      log_in_user!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = ["Username or Password was too smelly."]
      @user = User.new(user_params)
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:token] = nil
    redirect_to new_session_url
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

MyWorstProject-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

MyWorstProject-master/app/helpers/application_helper.rb
module ApplicationHelper
end

MyWorstProject-master/app/helpers/comments_helper.rb
module CommentsHelper
end

MyWorstProject-master/app/helpers/goals_helper.rb
module GoalsHelper
end

MyWorstProject-master/app/helpers/sessions_helper.rb
module SessionsHelper
end

MyWorstProject-master/app/helpers/users_helper.rb
module UsersHelper
end

MyWorstProject-master/app/views/goals/_form.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label for="title">Title</label>
<input type="text" name="goal[title]" value="<%= @goal.title %>" id="title">
<br>

<label for="content">Content</label>
<br>
<textarea name="goal[content]" rows="8" cols="120" id="content"><%= @goal.content %></textarea>
<br>

Access
<br>
<label>Private
  <input type="radio" name="goal[access]" value="Private" <%= @goal.check_if_private %>>
</label>

<label>PubicHair
  <input type="radio" name="goal[access]" value="Public" <%= @goal.check_if_public %>>
</label>

<br>

<button name="button">Submit</button>

MyWorstProject-master/app/views/goals/edit.html.erb
<h1>Edit <%= @goal.title %></h1>

<form action="<%= goal_url %>" method="post">

  <input type="hidden" name="_method" value="PATCH">

  <%= render "form" %>
</form>

MyWorstProject-master/app/views/goals/index.html.erb
<h1>Justoon is a guava</h1>
<h2>Goals Index</h2>

<ul>
  <% @goals.each do |goal| %>
  <li><a href="<%= goal_url(goal) %>"><%= goal.title %></a>
     - <%= goal.completion %></li>
  <% end %>
</ul>

<a href="<%= new_goal_url %>">Create Goal</a>
<br>

MyWorstProject-master/app/views/goals/new.html.erb
<h1>Create a Goal</h1>
<h6>(OR DON'T SEE IF I CARE)</h6>

<form action="<%= goals_url %>" method="post">
  <%= render "form" %>
</form>

MyWorstProject-master/app/views/goals/show.html.erb
<h1><%= @goal.title %> - <%= @goal.completion %></h1>



<% if @goal.user_id == current_user.id %>
<form action="<%= edit_goal_url(@goal) %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <button name="button">Edit Goal</button>
</form>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="DELETE">

  <button name="button" data-confirm="Goat's Blood?">Delete Goal</button>
</form>

<% unless @goal.is_complete? %>
<form action="<%= goal_complete_url(@goal) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <button name="button">Complete Goal</button>
</form>
<% end %>
<% end %>

<pre><p>
  <%= @goal.content %>
</p></pre>

<h2>COMMENTS</h2>
<ul>
  <li><%= render "comments/form", co_id: @goal.id, co_type: "Goal" %></li>
  <% @goal.comments.includes(:user).each do |comment| %>
  <li><%= render "comments/comment", comment: comment %></li>
  <% end %>
</ul>
<a href="<%= goals_url %>">Return to Goal Index</a>



<a href="<%= goals_url %>">Return to Index</a>